### ISSUE TITLE
Install button not showing up on some devices?

### ISSUE THREAD

**Issue by egroeper** [egroeper/hu-eduroam#16]
We had a user report about the "Wlan-Profil installieren" button not showing up on a
Sony Ericsson, sk17i (Xperia Mini Pro) with Android 4.0.4.

**Comment by der-eismann** [comment]
Propably because of very small screen size. Will be fixed with upcoming design changes.

**Comment by egroeper** [comment]
Should be fixed in 0.25.

**Comment by egroeper** [comment]
Should already be fixed...
