### ISSUE TITLE
Workaround for new Android permissions

### ISSUE THREAD

**Issue by egroeper** [egroeper/hu-eduroam#18]
Since Android 6.0 apps aren't allowed anymore to remove wifi configs they haven't created by themself.
So we need to make the user aware of the problem and help him to remove his existing wifi config ("eduroam" or "eduroam_5GHz").

sources:
https://developer.android.com/about/versions/marshmallow/android-6.0-changes.html#behavior-network
https://code.google.com/p/android/issues/detail?id=187347
https://code.google.com/p/android/issues/detail?id=192622

**Comment by egroeper** [comment]
We could at least open the wifi settings for the user and give them instructions:
http://stackoverflow.com/questions/7454416/open-wireless-settings-from-app

**Comment by der-eismann** [comment]
Great workaround, text should be clearly understandable for everyone.
