### ISSUE TITLE
MAC address not reported correctly on Android 6.0

### ISSUE THREAD

**Issue by der-eismann** [egroeper/hu-eduroam#19]
Android disabled the function to get the MAC address because of security reasons, instead it always shows a fake MAC address (02:00:00:00:00:00), I can confirm it with my LG G4.

http://stackoverflow.com/questions/33103798/how-to-get-wi-fi-mac-address-in-android-marshmallow

Maybe you should disable this method on API level >= 23 or implement the workaround mentioned in the link above.

**Comment by egroeper** [comment]
Thanks for notifying me.

**Comment by der-eismann** [comment]
MAC address now reported correctly, thanks.
