### ISSUE TITLE
Lock screen settings not always located in security settings

### ISSUE THREAD

**Issue by der-eismann** [egroeper/hu-eduroam#20]
Thanks for your idea to delete the screen lock after the installation, worked pretty well on my phone and should make it more attractive to some people.

Only one exception: The vendor-specific UIs sometimes have additional "screen lock settings", so you won't find any entry about that in the normal security settings that are opened by your app (see screenshots). I guess there is no better solution than yourssince all big vendors are doing stuff like that.

![screen_lock_settings](https://cloud.githubusercontent.com/assets/10406217/15866911/0b98186c-2ce1-11e6-8dfc-62c0c2110e6b.png)
![security_settings_1](https://cloud.githubusercontent.com/assets/10406217/15866910/0b98247e-2ce1-11e6-90d9-b0622ef1381e.png)
![security_settings_2](https://cloud.githubusercontent.com/assets/10406217/15866912/0b985d7c-2ce1-11e6-8b34-61ae785781b5.png)

**Comment by egroeper** [comment]
Thanks for reporting. But I currently don't think there is room for improvement here.
If you have specific suggestions how to improve this, please reopen this issue or file a new one.
